services:
  - type: web
    name: gdrm-weekend-getaway
    env: python
    plan: free  # Adjust the plan according to your needs
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json  # Path to the credentials file in the deployed environment
